spring:
  datasource:
    url: jdbc:mysql://localhost/office-building-management
    username: root
    password: root
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show:
          sql: true
      format_sql: true
  main:
    allow-circular-references: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE